name: Buil go app and deploy to Azure Web App

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Build the Go app
        run: |
          cd server
          cd cmd
          go build -o ../build/go-app.exe -v

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'miniiurl-server'
          slot-name: 'Production'
          publish-profile: ${{ secrets.azureWebAppPublishProfile }}
          package: build/go-app.exe
